# Generated by Django 4.0.1 on 2022-01-13 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('league', models.CharField(choices=[('NL', 'National League'), ('AL', 'American League')], default='NL', max_length=2)),
                ('award', models.CharField(choices=[('MVP', 'MVP'), ('CY', 'Cy Young'), ('ROTY', 'Rookie of the Year')], default='MVP', max_length=4)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.card')),
            ],
        ),
    ]
