# Generated by Django 4.0.1 on 2022-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('material', models.CharField(choices=[('P', 'Plastic'), ('G', 'Glass')], default='P', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='winner',
            options={'ordering': ['-year']},
        ),
    ]
