# Generated by Django 4.0.1 on 2022-01-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_case_alter_winner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='toys',
            field=models.ManyToManyField(to='main_app.Case'),
        ),
    ]
