# Generated by Django 4.0.1 on 2022-01-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_card_toys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='toys',
            new_name='cases',
        ),
    ]
